package schedule;

import java.util.*;
import java.util.stream.Collectors;

import model.Schedule;
import model.Solution;
import project.Activity;
import sun.reflect.generics.reflectiveObjects.NotImplementedException;

public class MogSequence extends Sequence {

  /**
   * Esta clase realiza las acciones para obtener la secuencia "S" por el modelo MOG
   */
  void startNextActivities() {
    Random random = new Random();
    /* Random para escoger la regla de prioridad
        Determine randomly a priority rule;
    (0) Lower duration: a solution s is generated by sequencing
        activities in non-decreasing order of the value of its duration;
    (2) Bigger number of successors activities: a solution s is generated
        by sequencing activities in non-increasing order of its numbers
        of successors activities;
    (3) Lower weight: a solution s is generated by sequencing activities
        in non-decreasing order of the value of its weight.
     */
    int method = random.nextInt(3);
    List<Activity> doableActivities = getDoableActivities(availableActivities);
    // Si no hay trabajos que se puedan hacer nos salimos del metodo
    if (doableActivities.size() == 0) {
      return;
    }

    int[] resourcesNeeded = new int[resources.length];
    for (int i = 0; i < resourcesNeeded.length; i++) {
      int finalI = i;
      resourcesNeeded[finalI] = doableActivities.stream()
          .mapToInt(activity -> activity.getResources()[finalI]).sum();
    }

    if(areAvailableResources(resourcesNeeded)){
      doableActivities.forEach(this::startActivity);
      return;
    }

    // Ordenamos los trabajos segun el metodo
    List<Activity> sortedActivities = getSortedActivitiesByMethod(doableActivities, method);

    List<Activity> shrinkList;
    // "sorteActivities" es la lista de trabajos ya ordenada
    // "shrinkListMaxIndex" representa el numero de items que vamos a coger la cantidad de trabajos disponibles
    // Sacamos una sublista escogiendo los primeros "shrinkListMaxIndex" items deacuerdo al random de %
    int shrinkListSize = random.nextInt(sortedActivities.size());
    int shrinkListMaxIndex = shrinkListSize == 0 ? 1 : shrinkListSize;
    shrinkList = sortedActivities.subList(0, shrinkListMaxIndex);
    //Buscamos trabajos hasta que ya no queden mas recursos disponibles o mas trabajos
    int activityTodoIndex;
    while (shrinkList.size() > 0) {
      activityTodoIndex = random.nextInt(shrinkList.size());
      startActivity(shrinkList.get(activityTodoIndex));
      shrinkList.remove(shrinkList.get(activityTodoIndex));
      // Vamos a quitar de la lista "shrinkList" el trabajo iniciado
      doableActivities = getDoableActivities(shrinkList);

      // Si ya no hay trabajos que se puedan haccer entoncnes no sasalimos del ciclo
      if(doableActivities.size() == 0){
        break;
      }
      // "sorteActivities" es la lista de trabajos ya ordenada
      // "shrinkListMaxIndex" representa el numero de items que vamos a coger la cantidad de trabajos disponibles
      // Sacamos una sublista escogiendo los primeros "shrinkListMaxIndex" items deacuerdo al random de %
      method = random.nextInt(3);
      sortedActivities = getSortedActivitiesByMethod(doableActivities, method);
      shrinkListSize = random.nextInt(sortedActivities.size());
      shrinkListMaxIndex = shrinkListSize == 0 ? 1 : shrinkListSize;
      shrinkList = sortedActivities.subList(0, shrinkListMaxIndex);
    }
  }

  private boolean areAvailableResources(int[] resources) {
    for (int j = 0; j < resources.length; j++) {
      if (resources[j] > this.resources[j].getAmount()) {
        return false;
      }
    }
    return true;
  }

  @Override
  public List<Solution> getSolutions(Schedule schedule) {
    Solution solution = new Solution(generateSequence(schedule), -1, -1);
    return  Collections.singletonList(solution);
  }

  private List<Activity> getSortedActivitiesByMethod(List<Activity> doableActivities, int method) {
    Comparator<Activity> comparator;
    switch (method) {
      case 0: {
        comparator = Comparator.comparingInt(Activity::getDuration);
        break;
      }
      case 1: {
        comparator = Comparator.comparingInt(activity -> -activity.getSuccessors().size());
        break;
      }
      case 2: {
        comparator = Comparator.comparingInt(activity -> activity.getWeight());
        break;
      }
      default:
        throw new RuntimeException("Opción: " + method);
    }
    return doableActivities.stream()
        .sorted(comparator)
        .collect(Collectors.toList());
  }
}
